usb: host: Do not compile test deprecated USB_OCTEON_EHCI
The USB_OCTEON_EHCI is deprecated and only selects proper driver so
there is no need to compile test it.  Since it selects
USB_EHCI_BIG_ENDIAN_MMIO it causes compilation failures on certain big
endian architectures (e.g. m68k):

    In file included from drivers/usb/host/ehci-mxc.c:19:0:
    drivers/usb/host/ehci.h: In function ‘ehci_readl’:
    drivers/usb/host/ehci.h:743:3: error:
        implicit declaration of function ‘readl_be’ [-Werror=implicit-function-declaration]

Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Krzysztof Kozlowski <krzk@kernel.org>
Link: https://lore.kernel.org/r/1577778392-570-1-git-send-email-krzk@kernel.org
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>