watchdog: m54xx: Add missing include
A recent cleanup removed the mm.h include from uaccess_no.h in
m68k. This breaks the build of the m54xx watchdog driver:

  drivers/watchdog/m54xx_wdt.c:49:9: error: implicit declaration of function '__raw_readl'

Due to magic include chains the inclusion of mm.h in uaccess_no.h pulled in io.h.

Include 'linux/io.h' explicitely to fix this.

Fixes: 9e860351550b ("m68knommu: Remove mm.h include from uaccess_no.h")
Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Thomas Gleixner <tglx@linutronix.de>
Cc: Wim Van Sebroeck <wim@linux-watchdog.org>
Cc: Guenter Roeck <linux@roeck-us.net>
Cc: linux-watchdog@vger.kernel.org
Reviewed-by: Guenter Roeck <linux@roeck-us.net>
Link: https://lore.kernel.org/r/87blmyjjtf.fsf@nanos.tec.linutronix.de
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Wim Van Sebroeck <wim@linux-watchdog.org>