Revert "net: dccp: initialize (addr,port) listening hashtable"
This reverts commit ec49d83f245453515a9b6e88324e27bbcb69fbae.

Cause build failures when DCCP is modular.

ERROR: "inet_hashinfo2_init" [net/dccp/dccp.ko] undefined!

Signed-off-by: David S. Miller <davem@davemloft.net>