Revert "pktgen: Allow configuration of IPv6 source address range"
This reverts commit 7786a1af2a6bceb07860ec720e74714004438834.

It causes build failures on 32-bit, for example:

   net/core/pktgen.o: In function `mod_cur_headers':
>> pktgen.c:(.text.mod_cur_headers+0xba0): undefined reference to `__umoddi3'

Signed-off-by: David S. Miller <davem@davemloft.net>